package com.wms.panchkula.ui.issueForProductionOrder.Model

import com.google.gson.annotations.SerializedName
import com.wms.panchkula.ui.goodsreceipt.model.IssueFromModel
import com.wms.panchkula.ui.production.model.batchCode.ProductionOrderStageModel.Value.ProductionOrdersStage
import com.wms.panchkula.ui.production.model.batchCode.ProductionOrderStageModel.Value.ProductionOrdersStage.ProductionOrderLine
import com.wms.panchkula.ui.purchase.model.PurchaseRequestModel
import java.io.Serializable

data class ProductionListModel(
    @SerializedName("odata.metadata") var odataMetadata: String,
    @SerializedName("odata.nextLink") var odataNextLink: String,
    var value: ArrayList<Value>,
    ):Serializable  {
    data class Value(
        var AbsoluteEntry: String,
        var DocumentNumber: String,
        var FGName: String,
        var SeriesCode: String,
        var ReceiptSeriesCode: String,
        var Series: String,
        var ItemNo: String,
        var ProductionOrderStatus: String,
        var ProductionOrderType: String,
        var PlannedQuantity: Double,
        var CompletedQuantity: Double,
        var RejectedQuantity: Double,
        var PostingDate: String,
        var DueDate: String,
        var ProductionOrderOriginEntry: Long? = null,
        var ProductionOrderOriginNumber: Long? = null,
        var ProductionOrderOrigin: String,
        var UserSignature: Long,
        var Remarks: Any? = null,
        var ClosingDate: String? = null,
        var ReleaseDate: String? = null,
        var CustomerCode: Any? = null,
        var Warehouse: String,
        var InventoryUOM: String? = null,
        var JournalRemarks: String,
        var TransactionNumber: Long? = null,
        var CreationDate: String,
        var Printed: String,
        var DistributionRule: String,
        var Project: String? = null,
        var DistributionRule2: String,
        var DistributionRule3: String,
        var DistributionRule4: String,
        var DistributionRule5: String,
        var UoMEntry: Long,
        var StartDate: String,
        var ProductDescription: String? = null,
        var Priority: Long,
        var RoutingDateCalculation: String,
        var UpdateAllocation: String,
        var SAPPassport: Any? = null,
        var AttachmentEntry: Any? = null,
        var U_PM: Double? = null,
        var U_Width: Double? = null,
        var U_GSM: Double? = null,
        var U_FLEX: Double? = null,
        var U_TBQ: Double? = null,
        var U_Length: Double? = null,
        var U_Cal: Any? = null,
        var U_QRCode: Any? = null,
        var U_QRPath: Any? = null,
        var ProductionOrderLines: List<ProductionOrderLine>,
        var ProductionOrdersSalesOrderLines: List<Any?>,
        var ProductionOrdersStages: List<ProductionOrdersStage>,
        var ProductionOrdersDocumentReferences: List<Any?>
    ) : Serializable

    data class ProductionOrdersStage(
        val Father: String,
        val Name: String,
        val ProductionOrderLines: List<ProductionOrderLine>,
        val SequenceNumber: Any,
        val StageEntry: Any,
        val StageId: String
    ):Serializable

    data class ProductionOrderLine(
        var isScanned : Int = 0,
        var DocumentAbsoluteEntry: Long= 0,
        var LineNumber: String ="",
        var ItemNo: String = "",
        var BaseQuantity: Double = 0.0,
        var PlannedQuantity: Double = 0.0,
        var IssuedQuantity: Double= 0.0,
        var IssueQuantity: Double= 0.0,
        var ProductionOrderIssueType: String? =null,
        var Batch: String? = "",
        var Serial: String? = "",
        var None: String? = "",
        var Warehouse: String= "",
        var VisualOrder: Long = 0,
        var DistributionRule: Any? = null,
        var LocationCode: Long = 0,
        var Project: Any? = null,
        var DistributionRule2: Any? = null,
        var DistributionRule3: Any? = null,
        var DistributionRule4: Any? = null,
        var DistributionRule5: Any? = null,
        var UoMEntry: Long = 0,
        var UoMCode: Long= 0,
        var WipAccount: Any? = null,
        var ItemType: String = "",
        var LineText: Any? = null,
        var AdditionalQuantity: Double= 0.0,
        var ResourceAllocation: Any? = null,
        var StartDate: String? = null,
        var EndDate: String? = null,
        var StageID: Any? = null,
        var RequiredDays: Double= 0.0,
        var ItemName: String? = null,
        var SerialNumbers: List<Any?> = listOf(),
        var BatchNumbers: List<Any?> = listOf(),
        var BinManaged: String?=null,


        //new keys
        var DocEntry: Int = 0,
        var ItemCode: String = "",
        var ItemDescription: String = "",
        var SystemNumber: Int = 0,
        var SerialNumber: String? = null,
        var ScanType: String = "",
        var Quantity: String = "",
        var FixedQuantity: String = "",
        var WareHouseCode: String = "",
        var UnitPrice: String = "",
        var BatchNumber: String? = "",
        var SystemSerialNumber: Long = 0,
        var InternalSerialNumber: String? = "",
        var NoneVal: String? = "",
        var U_Length: Double = 0.0,
        var U_Width: Double = 0.0,
        var U_GSM: Double = 0.0,
        var U_GW: Double = 0.0,
        var U_NW: Any? = null,
        var batchList : MutableList<ScanedOrderBatchedItems.Value> = mutableListOf(),
        var serialList : MutableList<ScanedOrderBatchedItems.Value> =  mutableListOf(),
        var noneList : MutableList<ScanedOrderBatchedItems.Value> =  mutableListOf(),
        var IssueFromModelList : MutableList<IssueFromModel.Value> = mutableListOf(),
        var binAllocationJSONs: ArrayList<PurchaseRequestModel.binAllocationJSONs>
        ): Serializable

}